version: '3.7'

services:
  # PHP-FPM - Service
  app:
    build:
      context: .
      dockerfile: ./docker-files/php/Dockerfile

    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html

    volumes:
      - ./:/var/www/html
      - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
      - app-network

  # NGINX - Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true

    ports:
      - "8100:80"
      - "8143:443"

    volumes:
      - ./:/var/www/html
      - ./docker-files/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-files/nginx/conf.d/default.conf:/etc/nginx/sites-available/default.conf
      - ./docker-files/nginx/nginx.conf:/etc/nginx/nginx.conf

    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge
